### ISSUE TITLE
DIAMOND option instead of BLASTP

### ISSUE THREAD

**Issue by jdwinkler** [Singh-Lab/DeMaSk#1]
Hi,

Thanks for your work on DeMaSk, it looks like a significant advance over the variant effect predictors I've looked at in the past. I was able to get it up and running easily, but I noticed that the initial homolog extraction/alignment (demask.homologs) step relies on BLASTP. I was wondering if I could substitute DIAMOND (https://github.com/bbuchfink/diamond) instead, which will significantly speed up the alignment step?

**Comment by daniel-munro** [comment]
Hello, I haven't tried it with DIAMOND, and currently the code doesn't allow for built-in handling of programs besides BLASTP. But I'll look into DIAMOND, and if it gives good results I'll add support for it. DeMaSk processes JSON-formatted BLASTP output, and I don't think DIAMOND has a JSON output option, so that would take some modification.

In the meantime, you could use DIAMOND as long as you can get the output into an aligned fasta file with the query as the first sequence (gaps in query are fine), to use as input for the demask.predict step. You can use the demask.homologs.passes_filters to filter homologs based on identity and gaps %, but that step is optional and doesn't have a huge effect. You may also want to retrain the linear model coefficients using demask.fit and DIAMOND on the built-in training proteins, especially if using a database other than UniRef90, which was used for the default coefficients.

**Comment by jdwinkler** [comment]
Yeah, it appears that diamond doesn't offer that option, so probably not a drop in replacement. I'll see if the diamond developer has plans to add JSON output format support in the future. I'm not sure it would be a big enough speed up to bother with additional development work since diamond is optimize for large batch queries, and I'm only processing the ~4,000 member proteomes for a range of  E. coli strains.

Thanks for the tips though, I will keep that in mind if the protein sets increase and size and DIAMOND or similar fast aligner becomes more necessary.
