### ISSUE TITLE
How to read the result

### ISSUE THREAD

**Issue by TobiasWinter97** [Singh-Lab/DeMaSk#3]
Hi there, I'm using the DeMaSk server to predict the amino acid mutation probability of my protein, the problem is, I cannot understand the output well, please help me out, thanks!

pos	WT	var	score	entropy	log2f_var	matrix
1	M	A	-0.3615	0.3314	-20.3430	-0.2641
1	M	C	-0.3670	0.3314	-20.3430	-0.2713
1	M	D	-0.4730	0.3314	-20.3430	-0.4100
1	M	E	-0.4632	0.3314	-20.3430	-0.3972
1	M	F	-0.3666	0.3314	-20.3430	-0.2707
1	M	G	-0.4424	0.3314	-20.3430	-0.3700
1	M	H	-0.4198	0.3314	-20.3430	-0.3404
1	M	I	-0.2110	0.3314	-7.0552	-0.1558
1	M	K	-0.4241	0.3314	-20.3430	-0.3460
1	M	L	-0.1729	0.3314	-6.0552	-0.1126
1	M	N	-0.4146	0.3314	-20.3430	-0.3336
1	M	P	-0.5325	0.3314	-20.3430	-0.4879
1	M	Q	-0.4067	0.3314	-20.3430	-0.3232
1	M	R	-0.4514	0.3314	-20.3430	-0.3817
1	M	S	-0.3929	0.3314	-20.3430	-0.3052
1	M	T	-0.3327	0.3314	-20.3430	-0.2263
1	M	V	-0.2350	0.3314	-5.4703	-0.1978
1	M	W	-0.4294	0.3314	-20.3430	-0.3529
1	M	Y	-0.4089	0.3314	-20.3430	-0.3261

for the first residue, which amnio acid should I used for following wet-lab mutation?

**Comment by daniel-munro** [comment]
Hello, the output includes one row for each possible amino acid substitution. The last three columns are the three features computed from the alignment and substitution matrix, described here [https://demask.princeton.edu/about/](https://demask.princeton.edu/about/)

The score column gives the impact predictions computed from those features using the trained linear model. Since the training dataset scores were rank-normalized, the unit of the predictions is the change in quantile across the fitness levels of all possible single-residue variants of a protein. Different DMS studies can represent protein 'fitness' differently, so the main thing to get from these scores is that they rank substitutions within the protein in terms of change in fitness/function. Low score = low fitness (big negative substitution impact).

So if you're looking to modify proteins based on these scores, you may want to choose the substitution with the lowest or highest score, depending on what you want to decrease or (possibly) increase fitness/function. And you may want to consider only a subset of possible substitutions, e.g. those requiring only one base mutation or those in a specific domain, depending on your needs.
